#!/usr/bin/env python3
"""
K304 -- TX19-BACK section 3: the inflected-variant fold.

Source: inflected_variants_library_v1.csv, generated by the Successor-Protocol seat from
the July mirror (a strict subset of the live 188, LOST:0 confirmed at K303).  It is a
CANDIDATE LIST, not a fold, and the seat said so: "roughly one row in eight wants
dropping."

Three things had to happen before any of it could land:
  1. RE-SPELL both sides.  The mirror predates K299, so forms carry `dont`/`arent`/`isnt`.
     Un-respelled, 8 rows looked like they referenced forms that do not exist live.
  2. Confirm each declared_form is actually live on the entry named.  After respelling,
     136/136 are.
  3. Drop what a generator cannot judge.  Some classes are mechanical, some are a read,
     and this script records which is which rather than blurring them.

DROPPED, mechanically detectable (7):
  infinitive after "to"   natural to had kids / natural to had children /
                          meant to had children / too lazy to had kids / easy for you to said
  modal + past            what should we actually did
  imperative + past       abolish capitalism and suffering ended
DROPPED, a read (1):
  nominal mis-shift       most lived are not that bad   ("lives" is the noun, not the verb)
KEPT despite a flag, because the flag was MY false positive (2):
  people said they are happy          -- reported speech legitimately keeps present tense
  what did not kill you makes you stronger -- idiomatic, and the live form is spelled this way

PLURAL: the seat retracted their own sweep argument after measuring it -- naive head-noun
pluralization gives 131 candidates and most are broken (circle of lifes, cherry picking
the worsts).  Curated to count nouns: 9, of which 3 survive a read.  Those 3 fold; the
other 6 are mass or idiomatic and the class closes.

REVIEW (19 rows, 8 objections): NOT FOLDED.  Floor-adjacent and firewall-delicate --
why-not-suicide, survivor-testimony, just-depressed, ableist-objection and the rest.
Returned to the library seat for a per-row pass.  A bulk fold there would put past-tense
distress phrasings next to a crisis floor without anyone having read them one at a time.
"""
import json, io, sys, os, re

CSV = "tools/omega/k304/inflected_variants_library_v1.csv"
DROP = {
  "natural to had kids", "natural to had children", "meant to had children",
  "too lazy to had kids", "easy for you to said", "what should we actually did",
  "abolish capitalism and suffering ended", "most lived are not that bad",
}
PLURAL_KEEP = {"first world problems", "luxury beliefs", "elite beliefs"}

CON = {"arent":"are not","cannot":"can not","cant":"can not","couldnt":"could not",
       "didnt":"did not","doesnt":"does not","dont":"do not","hadnt":"had not",
       "hasnt":"has not","havent":"have not","im":"i am","isnt":"is not","ive":"i have",
       "shouldnt":"should not","thats":"that is","theres":"there is","theyre":"they are",
       "wasnt":"was not","werent":"were not","wont":"will not","wouldnt":"would not",
       "youre":"you are","youve":"you have","its":"its","dont":"do not"}
def norm(s):
    s = s.lower().replace("-", " ").replace("'", "").replace("’", "")
    s = re.sub(r"[^a-z0-9 ]+", " ", s)
    out = []
    for p in s.split():
        out.extend(CON[p].split() if p in CON else [p])
    return " ".join(out)

def main(root="."):
    p = os.path.join(root, "src/components/omega-corpus-mrgrey.json")
    raw = io.open(p, encoding="utf-8", newline="").read()
    doc = json.loads(raw)
    assert json.dumps(doc, ensure_ascii=False, indent=2) + "\n" == raw, "round-trip not byte-exact"
    ents = doc["yurei_corpus"]["entries"]
    byid = {e["id"]: e for e in ents}
    allforms = {q["form"] for e in ents for q in e.get("patterns", [])}

    rows = [l.split(",") for l in
            io.open(os.path.join(root, CSV), encoding="utf-8").read().splitlines()[1:] if l.strip()]
    added = dropped = skipped = review = 0
    for batch, obj, eid, form, variant, shift in rows:
        f, v = norm(form), norm(variant)
        if batch == "REVIEW":                      review += 1;  continue
        if batch == "PLURAL" and v not in PLURAL_KEEP: dropped += 1; continue
        if v in DROP:                              dropped += 1; continue
        e = byid.get(eid)
        assert e is not None, f"{eid} not live"
        src = next((q for q in e["patterns"] if q["form"] == f), None)
        assert src is not None, f"{eid}: declared form {f!r} not live (respelling failed?)"
        assert norm(v) == v, f"pre-normalized corpus law: {v!r}"
        if v in allforms:                          skipped += 1; continue   # would mint a collision
        e["patterns"].append({"form": v, "mode": src["mode"], "weight": src["weight"]})
        allforms.add(v); added += 1

    io.open(p, "w", encoding="utf-8", newline="").write(
        json.dumps(doc, ensure_ascii=False, indent=2) + "\n")
    n = len(ents); tot = sum(len(e.get("patterns", [])) for e in ents)
    print(f"  folded {added} · dropped {dropped} · already-declared (skipped, no new collision) {skipped} · REVIEW held back {review}")
    print(f"  mrgrey: {n} entries / {tot} forms")

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else ".")
