#!/usr/bin/env python3
"""
apply_wuld_wrap.py - wrap the Video-Editing project's Apparatus artifact for wuld.ink.

The Apparatus (`illogically-is-apparatus.html`) is authored and REGENERATED by the
Video Editing project (`build_apparatus.py`). Never hand-edit it here. This script
re-applies wuld.ink's three additive regions to a freshly vendored artifact so a
re-vendor is: drop the new file in, run this, ship.

Regions (each marked, each additive, zero content restyling):
  wuld:head      - description / canonical / OG+Twitter / minimal <a> + line styles
                   (the artifact ships NO link styling; without this the sanctioned
                   link lines render browser-default blue against the film register)
  wuld:links     - the "PDF" line under the title, per the handoff section 3.2;
                   the film-links line ships commented until the URLs exist
  wuld:colophon  - one mono line back to wuld.ink (the page carries no site chrome,
                   so without it a visitor arriving from YouTube has no way in)

Anchors must each occur EXACTLY once or the script fails loud - a regenerated
artifact that moved them gets adjudicated, never silently half-wrapped.

Usage:
  python3 tools/apparatus/apply_wuld_wrap.py --in <artifact.html> --out <index.html>
  python3 tools/apparatus/apply_wuld_wrap.py --in x.html --check   # anchors only
"""
import argparse, re, sys

DESC = ("Sources, method and chronology of the essay film Illogically Is. "
        "The film carries no credits by rule; this document is its only credit sequence.")
TITLE = "Illogically Is &mdash; The Apparatus"
URL = "https://wuld.ink/illogically-is/apparatus/"
OG = "https://wuld.ink/assets/og-default.png"

HEAD = f"""
<!-- wuld:head -->
<meta name="description" content="{DESC}">
<link rel="canonical" href="{URL}">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<meta property="og:title" content="{TITLE}">
<meta property="og:description" content="{DESC}">
<meta property="og:type" content="article">
<meta property="og:url" content="{URL}">
<meta property="og:image" content="{OG}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:site_name" content="wuld.ink">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{TITLE}">
<meta name="twitter:description" content="{DESC}">
<meta name="twitter:image" content="{OG}">
<style>
a{{color:var(--red);text-decoration:none;border-bottom:1px solid var(--rule)}}
a:hover,a:focus-visible{{border-bottom-color:var(--red)}}
.wuld-line{{font:.8rem/1.6 "IBM Plex Mono",ui-monospace,monospace;letter-spacing:.04em;color:var(--dim);margin:-.4rem 0 1.8rem}}
.wuld-colophon{{font:.8rem/1.6 "IBM Plex Mono",ui-monospace,monospace;letter-spacing:.04em;color:var(--dim);margin:3.5rem 0 0;padding-top:1.2rem;border-top:1px solid var(--rule)}}
</style>
<!-- /wuld:head -->"""

LINKS = """
<!-- wuld:links -->
<p class="wuld-line">The film: <a href="https://youtu.be/EAvxK0f3oRo" rel="noopener">YouTube</a> &middot; this document as <a href="illogically-is-apparatus.pdf">PDF</a></p>
<!-- Vimeo and the Internet Archive join the line above when those URLs exist (handoff 3.2). Nothing else changes. -->
<!-- /wuld:links -->"""

COLOPHON = """
<!-- wuld:colophon -->
<p class="wuld-colophon">W.U.L.D.: Incorporated &middot; <a href="/">wuld.ink</a></p>
<!-- /wuld:colophon -->"""

INSERTS = [("</title>", HEAD, "after"), ("</h1>", LINKS, "after"), ("</main>", COLOPHON, "before")]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="src", required=True)
    ap.add_argument("--out", dest="out")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    t = open(a.src, encoding="utf-8").read()

    if "wuld:head" in t:
        sys.exit("FAIL: input already carries wuld regions - vendor the clean artifact")
    for anchor, _, _ in INSERTS:
        n = t.count(anchor)
        if n != 1:
            sys.exit(f"FAIL: anchor {anchor} occurs {n}x, expected 1 - artifact moved, adjudicate")
    if t.count("<script") or "://" in t.split("</head>", 1)[1]:
        sys.exit("FAIL: artifact gained a script or an external ref - adjudicate before shipping")
    print("anchors OK (1x each) - artifact script-free, no external refs in body")
    if a.check:
        return

    for anchor, block, where in INSERTS:
        t = t.replace(anchor, anchor + block if where == "after" else block + anchor, 1)

    back = re.sub(r"\n<!-- wuld:(head|links|colophon) -->.*?<!-- /wuld:\1 -->", "", t, flags=re.S)
    if back != open(a.src, encoding="utf-8").read():
        sys.exit("FAIL: delta is not isolated to the three marked regions")
    print("reversible OK - stripping the regions reproduces the artifact byte-exact")

    if not a.out:
        sys.exit("FAIL: --out required when not --check")
    open(a.out, "w", encoding="utf-8", newline="\n").write(t)
    print(f"wrote {a.out} ({len(t.encode('utf-8'))} B)")


if __name__ == "__main__":
    main()
