#!/usr/bin/env python3
"""
apply_wuld_wrap.py - wrap the Video-Editing project's Apparatus artifact for wuld.ink.

The Apparatus (`illogically-is-apparatus.html`) is authored and REGENERATED by the
Video Editing project (`build_apparatus.py`). Never hand-edit it here. This script
re-applies wuld.ink's three additive regions to a freshly vendored artifact so a
re-vendor is: drop the new file in, run this, ship.

Regions (each marked, each additive, zero content restyling):
  wuld:head      - description / canonical / OG+Twitter / minimal <a> + line styles
                   (the artifact ships NO link styling; without this the sanctioned
                   link lines render browser-default blue against the film register)
  wuld:links     - the "PDF" line under the title, per the handoff section 3.2;
                   the film-links line ships commented until the URLs exist
  wuld:colophon  - one mono line back to wuld.ink (the page carries no site chrome,
                   so without it a visitor arriving from YouTube has no way in)

Anchors must each occur EXACTLY once or the script fails loud - a regenerated
artifact that moved them gets adjudicated, never silently half-wrapped.

Usage:
  python3 tools/apparatus/apply_wuld_wrap.py --in <artifact.html> --out <index.html>
  python3 tools/apparatus/apply_wuld_wrap.py --in x.html --check   # anchors only
"""
import argparse, re, sys

VARIANTS = {
    # The film. These values are byte-frozen: a change here rewrites the shipped
    # /illogically-is/apparatus/ page, so any edit must be re-gated against it.
    "film": dict(
        desc=("Sources, method and chronology of the essay film Illogically Is. "
              "The film carries no credits by rule; this document is its only credit sequence."),
        title="Illogically Is &mdash; The Apparatus",
        url="https://wuld.ink/illogically-is/apparatus/",
        og="https://wuld.ink/assets/og-default.png",
        acc="--red", line="--rule", mut="--dim",
        # The film artifact defines no a{} of its own, so the wrap supplies one.
        astyle=("a{{color:var({acc});text-decoration:none;border-bottom:1px solid var({line})}}\n"
                "a:hover,a:focus-visible{{border-bottom-color:var({acc})}}\n"),
        links=('<p class="wuld-line">The film: <a href="https://youtu.be/EAvxK0f3oRo" rel="noopener">YouTube</a>'
               ' &middot; this document as <a href="illogically-is-apparatus.pdf">PDF</a></p>\n'
               '<!-- Vimeo and the Internet Archive join the line above when those URLs exist (handoff 3.2). Nothing else changes. -->'),
    ),
    # The companion short. Its artifact declares its OWN custom properties
    # (--acc / --line / --mut, not the film's --red / --rule / --dim), so the
    # injected styles have to name those or every link ships unstyled.
    # NO VIDEO LINK YET, deliberately: the upload is Unlisted under the binding
    # order in docs/wuld_ink_handoff_dot.md section 4, and linking it from a
    # public page would defeat that. The line goes in when the short is Public.
    "dot": dict(
        desc=("Sources, method and verification of the companion short to the essay film Illogically Is. "
              "The short carries no credits by rule; this document is its only credit sequence."),
        title="&ldquo;.&rdquo; &mdash; The Apparatus",
        url="https://wuld.ink/illogically-is/dot/apparatus/",
        og="https://wuld.ink/assets/og-default.png",
        acc="--acc", line="--line", mut="--mut",
        # NO a{} here. The dot artifact styles its own links deliberately --
        # a{color:inherit;text-decoration:underline;text-decoration-color:var(--acc)}
        # -- and it sits AFTER this block in source order, so an injected a{}
        # rule loses the cascade and ships as dead CSS. Restyling the content is
        # also what handoff-dot section 3.1 forbids. Only the two wrap classes.
        astyle="",
        links=('<p class="wuld-line">The film: <a href="/illogically-is/">Illogically Is</a>'
               ' &middot; this document as <a href="dot-apparatus.md">Markdown</a></p>\n'
               '<!-- The short\'s own YouTube / Vimeo / Internet Archive links join the line above once it is PUBLIC. -->\n'
               '<!-- It is Unlisted until the binding order completes (handoff-dot section 4); do not link it here before then. -->'),
    ),
    # The argument-library showcase. Unlike the other two, this artifact is BUILT here
    # from Markdown (build_libshow_apparatus.py) because that is the form the video seat
    # ships it in. It reuses the dot artifact's custom properties (--acc / --line / --mut)
    # and, like the dot, declares its own a{} AFTER this block, so an injected a{} would
    # lose the cascade and ship as dead CSS: astyle stays empty.
    # NO FILM LINK YET, deliberately: the cut goes to the JosiahSCooper channel first and
    # is reposted to the WULD channel after (handout section 3). Nothing is linked until
    # it is public.
    "libshow": dict(
        desc=("Sources, method and verification of the showcase film for the efilist argument library. "
              "The film carries no credits by rule; this document is its only credit sequence."),
        title="The Argument Library &mdash; The Apparatus",
        url="https://wuld.ink/argument-library/apparatus/",
        og="https://wuld.ink/assets/og-default.png",
        acc="--acc", line="--line", mut="--mut",
        astyle="",
        links=('<p class="wuld-line">The library: <a href="https://library.wuld.ink/">library.wuld.ink</a>'
               ' &middot; this document as <a href="argument-library-apparatus.md">Markdown</a></p>\n'
               '<!-- The film\'s own YouTube link joins the line above once it is PUBLIC: the JosiahSCooper -->\n'
               '<!-- cut first, the W.U.L.D. repost after. Do not link either before the film is public. -->'),
    ),
}


def blocks(v):
    head = f"""
<!-- wuld:head -->
<meta name="description" content="{v['desc']}">
<link rel="canonical" href="{v['url']}">
<link rel="icon" type="image/svg+xml" href="/favicon.svg">
<meta property="og:title" content="{v['title']}">
<meta property="og:description" content="{v['desc']}">
<meta property="og:type" content="article">
<meta property="og:url" content="{v['url']}">
<meta property="og:image" content="{v['og']}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:site_name" content="wuld.ink">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="{v['title']}">
<meta name="twitter:description" content="{v['desc']}">
<meta name="twitter:image" content="{v['og']}">
<style>
{v['astyle'].format(acc=v['acc'], line=v['line'])}.wuld-line{{font:.8rem/1.6 "IBM Plex Mono",ui-monospace,monospace;letter-spacing:.04em;color:var({v['mut']});margin:-.4rem 0 1.8rem}}
.wuld-colophon{{font:.8rem/1.6 "IBM Plex Mono",ui-monospace,monospace;letter-spacing:.04em;color:var({v['mut']});margin:3.5rem 0 0;padding-top:1.2rem;border-top:1px solid var({v['line']})}}
</style>
<!-- /wuld:head -->"""
    links = "\n<!-- wuld:links -->\n" + v['links'] + "\n<!-- /wuld:links -->"
    colophon = """
<!-- wuld:colophon -->
<p class="wuld-colophon">W.U.L.D.: Incorporated &middot; <a href="/">wuld.ink</a></p>
<!-- /wuld:colophon -->"""
    return head, links, colophon


def inserts(v):
    head, links, colophon = blocks(v)
    return [("</title>", head, "after"), ("</h1>", links, "after"), ("</main>", colophon, "before")]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="src", required=True)
    ap.add_argument("--out", dest="out")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--variant", choices=sorted(VARIANTS), default="film")
    a = ap.parse_args()
    t = open(a.src, encoding="utf-8").read()
    INSERTS = inserts(VARIANTS[a.variant])

    if "wuld:head" in t:
        sys.exit("FAIL: input already carries wuld regions - vendor the clean artifact")
    for anchor, _, _ in INSERTS:
        n = t.count(anchor)
        if n != 1:
            sys.exit(f"FAIL: anchor {anchor} occurs {n}x, expected 1 - artifact moved, adjudicate")
    # An external REF is something the browser will fetch: an attribute or a CSS url() whose
    # value points off-page. A bare "://" substring is not that -- it also matches a URL printed
    # as text for a reader to type, which is exactly what the hash-shot paragraph does, and
    # rewording the instruction to get past a checker would damage the sentence the shot exists
    # to support. Match the reference, not the marker.
    body = t.split("</head>", 1)[1]
    ref = re.compile(
        r"""(?:\b(?:href|src|srcset|action|formaction|poster|data|codebase|cite|background)"""
        r"""\s*=\s*["']?\s*|\burl\(\s*["']?|@import\s+["']?)(?:https?:)?//""",
        re.I)
    hit = ref.search(body)
    if t.count("<script") or hit:
        what = "a script" if t.count("<script") else "an external ref: " + repr(
            body[max(0, hit.start() - 30):hit.end() + 40])
        sys.exit("FAIL: artifact gained " + what + " - adjudicate before shipping")
    print("anchors OK (1x each) - artifact script-free, no external refs in body")
    if a.check:
        return

    for anchor, block, where in INSERTS:
        t = t.replace(anchor, anchor + block if where == "after" else block + anchor, 1)

    back = re.sub(r"\n<!-- wuld:(head|links|colophon) -->.*?<!-- /wuld:\1 -->", "", t, flags=re.S)
    if back != open(a.src, encoding="utf-8").read():
        sys.exit("FAIL: delta is not isolated to the three marked regions")
    print("reversible OK - stripping the regions reproduces the artifact byte-exact")

    if not a.out:
        sys.exit("FAIL: --out required when not --check")
    open(a.out, "w", encoding="utf-8", newline="\n").write(t)
    print(f"wrote {a.out} ({len(t.encode('utf-8'))} B)")


if __name__ == "__main__":
    main()
